# Generated by Django 5.1.2 on 2025-01-06 10:42

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(16)])),
                ('expiry_date', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_expiry_date', message='Expiry date must be in the format MM/YY', regex='^(0[1-9]|1[0-2])\\/[0-9]{2}$')])),
                ('cvv', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(3)])),
            ],
        ),
    ]
