# Generated by Django 5.1.2 on 2025-01-06 10:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_accountcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcard',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountcard',
            name='cvv',
            field=models.IntegerField(help_text="Karta CVV kodini kiritishingiz kerak. (Etibor bering 3ta dan katta va kichik bo'lmasin)", validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='accountcard',
            name='expiry_date',
            field=models.CharField(help_text='Karta tugash muddatini kiritishingiz kerak. (Etibor bering MM/YY formatida)', max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_expiry_date', message='Expiry date must be in the format MM/YY', regex='^(0[1-9]|1[0-2])\\/[0-9]{2}$')]),
        ),
        migrations.AlterField(
            model_name='accountcard',
            name='name',
            field=models.CharField(help_text='Karta egasi ism familiyasini kiritishingiz kerak', max_length=100),
        ),
        migrations.AlterField(
            model_name='accountcard',
            name='number',
            field=models.IntegerField(help_text="Karta raqamini kiritishingiz kerak. (Etibor bering 16ta dan katta va kichik bo'lmasin)", validators=[django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(16)]),
        ),
    ]
