# Generated by Django 5.1.2 on 2025-01-06 11:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_accountcard_user_alter_accountcard_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcard',
            name='cvv',
            field=models.IntegerField(help_text="Karta CVV kodini kiritishingiz kerak. (Etibor bering 3ta dan katta va kichik bo'lmasin)", validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='accountcard',
            name='number',
            field=models.IntegerField(help_text="Karta raqamini kiritishingiz kerak. (Etibor bering 16ta dan katta va kichik bo'lmasin)", validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='accountcard',
            name='user',
            field=models.ForeignKey(help_text='Karta egasi User', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
