# Generated by Django 5.1.2 on 2025-01-06 11:09

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_accountcard_cvv_alter_accountcard_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcard',
            name='cvv',
            field=models.IntegerField(help_text="Karta CVV kodini kiritishingiz kerak. (Etibor bering 3ta dan katta va kichik bo'lmasin)", validators=[authentication.models.check_value_cvv]),
        ),
        migrations.AlterField(
            model_name='accountcard',
            name='number',
            field=models.IntegerField(help_text="Karta raqamini kiritishingiz kerak. (Etibor bering 16ta dan katta va kichik bo'lmasin)", validators=[authentication.models.check_value_number]),
        ),
    ]
