# Generated by Django 5.1.2 on 2024-11-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time', models.DurationField()),
                ('directors', models.CharField(max_length=255)),
                ('actors', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trailer', models.URLField()),
                ('year', models.IntegerField()),
                ('is_movie', models.BooleanField(default=False)),
                ('is_serie', models.BooleanField(default=False)),
                ('genre', models.ManyToManyField(to='movie.genre')),
            ],
        ),
    ]
