# Generated by Django 5.1.2 on 2024-11-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='banner',
            field=models.ImageField(null=True, upload_to='films/banner/'),
        ),
        migrations.AddField(
            model_name='film',
            name='card',
            field=models.ImageField(null=True, upload_to='films/card/'),
        ),
    ]
