# Generated by Django 5.1.2 on 2024-12-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_film_banner_film_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
