# Generated by Django 5.1.2 on 2024-12-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_film_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='title_image',
            field=models.ImageField(null=True, upload_to='films/title/'),
        ),
    ]
