# Generated by Django 5.1.2 on 2024-12-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_film_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='title_image',
            field=models.FileField(null=True, upload_to='films/title/'),
        ),
    ]
