# Generated by Django 5.1.2 on 2024-12-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_film_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
