# Generated by Django 5.1.2 on 2025-01-17 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_film_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
