# Generated by Django 5.1.2 on 2025-01-20 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_film_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.film')),
            ],
            options={
                'verbose_name': 'Kino Trailerlari',
                'verbose_name_plural': 'Kino Trailerlari',
                'indexes': [models.Index(fields=['film', 'date_created'], name='movie_filmt_film_id_1fbf0e_idx')],
            },
        ),
    ]
