# Generated by Django 5.1.2 on 2025-01-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_film_time_alter_film_video_file_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
