# Generated by Django 5.1.2 on 2025-01-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_alter_film_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='banner',
            field=models.ImageField(null=True, upload_to='series/banner/'),
        ),
    ]
